"""Orchestration for Mode B (business-rules fold) and Mode C (screen reorder) --
phase-06 Requirements 2 and 3. Both are project-level units, not per-feature: Mode B
runs ONCE against `docs/system/business-rules.md` -> `docs/generated/behavior-logic.md`;
Mode C runs once PER `docs/screens/{slug}/spec.md`. Both reuse the exact staging /
sentinel / pre-swap-backup / atomic-swap machinery `_audience_split_migrate_lib.py`
already built for Mode A (CONSTRAINT 1: staging-first, no live write before validation,
no original deleted before the sentinel commits) -- neither mode invents a second
safety story.

Stdlib only.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _audience_split_migrate_lib import (  # noqa: E402
    _atomic_copy, _atomic_write_text, _swap_one, has_feature_sentinel, MigrationOutcome,
    staging_unit_dir, write_feature_sentinel,
)
from _audience_split_mode_b_lib import (  # noqa: E402
    bl_codes, fold_business_rules, FOLD_H2_HEADING, parse_business_rules,
)
from _audience_split_mode_c_lib import compose_mode_c, resolve_layout_rule_ids  # noqa: E402
from _audience_split_probe_lib import HAND_EDITED, probe_file  # noqa: E402

BUSINESS_RULES_REL = ("system", "business-rules.md")
BEHAVIOR_LOGIC_REL = ("generated", "behavior-logic.md")
_BACKUP_SUFFIX = ".pre-swap-backup"


def _backup_path(unit_dir: Path, name: str) -> Path:
    return unit_dir / (name + _BACKUP_SUFFIX)


def migrate_business_rules(docs_root: Path, project_root: Path) -> MigrationOutcome:
    """Mode B, run once. Absence of either file is a legitimate no-op -- `business-
    rules.md` may already be gone (a prior run, or a repo that never had it) and
    `behavior-logic.md` is generated by an EARLIER pass this migration does not own.

    Re-entry is guarded by the ARTIFACT (`FOLD_H2_HEADING` actually present in the live
    `behavior-logic.md`), never by the sentinel alone -- silent-data-corruption fix: the
    sentinel under `docs/.migrate-v27/` is realistically losable (a dot-directory under
    `docs/` a consumer may gitignore or clean), and `business-rules.md` is never deleted
    by this function (deletion is `--reviewed`-gated), so a sentinel-only guard let a
    second run re-parse the still-present source and APPEND a second fold section --
    cumulative on every re-run, exit 0, sentinel written, nothing warns. Checking the
    marker FIRST (before the sentinel) makes the sentinel a pure resume-speed
    optimization again: it is (re)written on the marker-detected path too, so a
    subsequent run stays cheap, but correctness never depends on it existing."""
    br_path = docs_root / BUSINESS_RULES_REL[0] / BUSINESS_RULES_REL[1]
    bl_path = docs_root / BEHAVIOR_LOGIC_REL[0] / BEHAVIOR_LOGIC_REL[1]
    unit_dir = staging_unit_dir(docs_root, "system", "business-rules")
    slug = "business-rules"

    if not br_path.is_file():
        return MigrationOutcome(slug, "no-op", True, "business-rules.md absent -- nothing to fold")
    if not bl_path.is_file():
        return MigrationOutcome(slug, "skipped-no-target", False,
                                "behavior-logic.md not found -- cannot fold into it")

    bl_text = bl_path.read_text(encoding="utf-8", errors="replace")
    if FOLD_H2_HEADING in bl_text:
        unit_dir.mkdir(parents=True, exist_ok=True)
        write_feature_sentinel(unit_dir)
        return MigrationOutcome(slug, "no-op", True,
                                "business-rules.md already folded into behavior-logic.md "
                                "(fold marker present) -- sentinel re-written")
    if has_feature_sentinel(unit_dir):
        return MigrationOutcome(slug, "no-op", True, "already migrated (sentinel present)")

    verdict = probe_file(br_path, project_root)
    if verdict.verdict == HAND_EDITED:
        return MigrationOutcome(slug, "skipped-hand-edited", True,
                                f"hand-edited ({verdict.reason}) -- retained, never folded")

    rules = parse_business_rules(br_path.read_text(encoding="utf-8", errors="replace"))
    folded = fold_business_rules(bl_text, rules)

    pre_codes = bl_codes(bl_text)
    post_codes = bl_codes(folded)
    if not pre_codes.issubset(post_codes):
        return MigrationOutcome(slug, "failed-validation", False,
                                f"fold dropped BL### code(s): {sorted(pre_codes - post_codes)}")

    unit_dir.mkdir(parents=True, exist_ok=True)
    _atomic_copy(bl_path, _backup_path(unit_dir, "behavior-logic.md"))
    _atomic_write_text(unit_dir / "behavior-logic.md", folded)

    import validate_behavior_logic as _vbl  # local import: scripts/ already on sys.path
    result = _vbl.validate(plan_dir=docs_root, root=project_root,
                            single_file=unit_dir / "behavior-logic.md")
    if result["summary"]["critical"]:
        return MigrationOutcome(slug, "failed-validation", False,
                                f"staged fold failed validation: {result['issues']}")

    _swap_one(unit_dir / "behavior-logic.md", bl_path)
    write_feature_sentinel(unit_dir)
    return MigrationOutcome(slug, "migrated", True, "business-rules.md folded into behavior-logic.md")


def migrate_screen(screen_dir: Path, project_root: Path, docs_root: Path) -> MigrationOutcome:
    """Mode C, one screen dir at a time. Pure reordering, no LLM pass (Requirement 3)."""
    spec_path = screen_dir / "spec.md"
    slug = screen_dir.name
    unit_dir = staging_unit_dir(docs_root, "screens", slug)

    if not spec_path.is_file():
        return MigrationOutcome(slug, "no-op", True, "no spec.md -- nothing to reorder")
    if has_feature_sentinel(unit_dir):
        return MigrationOutcome(slug, "no-op", True, "already migrated (sentinel present)")

    old_text = spec_path.read_text(encoding="utf-8", errors="replace")
    if "## Screen Layout" not in old_text:
        # Already reordered (or never had the old wrapper) -- I1: confirm, don't infer.
        unit_dir.mkdir(parents=True, exist_ok=True)
        write_feature_sentinel(unit_dir)
        return MigrationOutcome(slug, "confirmed-v27", True,
                                "no '## Screen Layout' wrapper present; sentinel written")

    verdict = probe_file(spec_path, project_root)
    if verdict.verdict == HAND_EDITED:
        return MigrationOutcome(slug, "skipped-hand-edited", True,
                                f"hand-edited ({verdict.reason}) -- retained, never reordered")

    new_text = compose_mode_c(old_text)

    from validate_reading_guide_db_impact import check_source_walkthrough
    issues = check_source_walkthrough(new_text, str(spec_path))
    if any(i["severity"] == "critical" for i in issues):
        return MigrationOutcome(slug, "failed-validation", False,
                                f"reordered spec failed validation: {issues}")
    fired = resolve_layout_rule_ids(new_text)
    if fired:
        return MigrationOutcome(slug, "failed-validation", False,
                                f"reordered spec trips layout rule_id(s): {fired}")

    unit_dir.mkdir(parents=True, exist_ok=True)
    _atomic_copy(spec_path, _backup_path(unit_dir, "spec.md"))
    _atomic_write_text(unit_dir / "spec.md", new_text)
    _swap_one(unit_dir / "spec.md", spec_path)
    write_feature_sentinel(unit_dir)
    return MigrationOutcome(slug, "migrated", True, "screen-spec reordered to Phase 02 BA-first order")
